server:
  port: 8470
logging:
  file: /java/C2S_LOGS/iexhub-pix-pdq/iexhubPixPdq.log
  level:
    gov.samhsa.c2s.iexhubpixpdq: info
    org.modelmapper: info
c2s:
  iexhub-pix-pdq:
    pixManagerServiceEndPoint: http://bhitsdevhie01/openempi-admin/services/PIXManager_Port_Soap12
    pixDomainId: 1.3.6.1.4.1.21367.13.20.205
    pixDomainName: FEI-DEV-IEXHUB
    globalDomainId: 2.16.840.1.113883.4.357
    fhir:
      # configure fhir server base url
      serverUrl: http://bhitsdevhie01/hapi-fhir-jpaserver/baseStu3
      clientSocketTimeoutInMs: 768000
---
spring:
  profiles: docker
c2s:
  iexhub-pix-pdq:
    pixManagerServiceEndPoint: http:/openempi.c2s.com:8080/openempi-admin/services/PIXManager_Port_Soap12
    fhiir:
      # configure fhir server base url
      serverUrl: http://hapi-fhir.c2s.com:8080/hapi-fhir-jpaserver/baseStu3