server:
  port: 8470
logging:
  file: /java/C2S_LOGS/iexhub-pix-pdq/iexhubPixPdq.log
  level:
    gov.samhsa.c2s.iexhubpixpdq: info
    org.modelmapper: info
c2s:
  iexhub-pix-pdq:
    pixManagerServiceEndPoint: http://bhitsdevhie01/openempi-admin/services/PIXManager_Port_Soap12
    globalDomainId: 2.16.840.1.113883.4.357
    globalDomainIdTypeCode: hl7
    fhir:
      capability-statement:
        publisher: BHITS
        software:
          name: Consent2Share IExHub PIX/PDQ
          version: @project.version@
        implementation:
          description: ${c2s.iexhub-pix-pdq.fhir.capability-statement.software.name}
---
spring:
  profiles: docker
c2s:
  iexhub-pix-pdq:
    pixManagerServiceEndPoint: http://openempi.c2s.com:8080/openempi-admin/services/PIXManager_Port_Soap12
    fhir:
      # configure fhir server base url
      serverUrl: http://hapi-fhir.c2s.com:8080/hapi-fhir-jpaserver/baseStu3